### ISSUE TITLE
Hashtags with cyrillic symbols are ignored

### ISSUE THREAD

**Issue by bodrovis** [gregjacobs/Autolinker.js#115]
Hello and many thanks for this great library!

I am supporting a service with both latin and cyrillic characters. Recently I noticed that Autolinker does not add links for Twitter hashtags with cyrillic symbols, whereas it does work for latin. For example, `#НашФутбол #рфпл` those hashtags are ignored completely.

**Comment by gregjacobs** [comment]
Fixed in 0.24.0

**Comment by bodrovis** [comment]
My thanks!
