### ISSUE TITLE
Autolinker parses "hello:.........world" as a link. Why?

### ISSUE THREAD

**Issue by danneu** [gregjacobs/Autolinker.js#116]
I use Autolinker.js to parse links in my website's chatbox. Some user's text was parsed as a link and it was of the format `<text>:.<text>` where the number of periods can be 1+, e.g. `hello:...world` and `hello:wo.....rld` will linkify.

Seems a bit aggressive even if it may be technically correct according to some spec. 

What do you think?

**Comment by erwinvaneyk** [comment]
.world is a gTLD so that would explain why it is converted. However, a domain cannot have multiple consecutive dots in its domain-name (see https://lists.isc.org/pipermail/bind-users/2011-January/082725.html). So in my opinion this is a bug.

**Comment by gregjacobs** [comment]
Good call, definitely too aggressive. Will see what I can do.
