### ISSUE TITLE
Link not fully created when containing { or }

### ISSUE THREAD

**Issue by asiminiceanu** [gregjacobs/Autolinker.js#120]
Hello,

I have the following link that it is not parsed correctly using 0.18.1:
```
https://aaa.com?bbb={ccc}
```

It results in:
```html
<a href="https://aaa.com?bbb=" target="_blank">https://aaa.com?bbb=</a>{ccc}
```

My call to the link method is:

```javascript
text = Autolinker.link(
                        message.text, 
                        {
                            twitter: false,
                            replaceFn : function(autolinker, match) {
                                var tag = autolinker.getTagBuilder().build(match);  
                                tag.setInnerHtml(match.getMatchedText());
                                return tag; 
                            }
                        }
                   );
```

**Comment by gregjacobs** [comment]
Hey, so `{` and `}` aren't actually valid in a url. They need to be %-encoded into `https://aaa.com?bbb=%7Bccc%7D`

Unfortunately Autolinker can't auto-link these without violating the RFC. See the first answer here for an explanation: http://stackoverflow.com/questions/1547899/which-characters-make-a-url-invalid
