### ISSUE TITLE
Protocol detection issue

### ISSUE THREAD

**Issue by asiminiceanu** [gregjacobs/Autolinker.js#121]
I have the following text entered without a space and the generated link is invalid:

```
enterprisehttp://blog.kodiakptt.com
```

Results in:

```html
enter<a href="prisehttp://blog.kodiakptt.com" target="_blank">prisehttp://blog.kodiakptt.com</a>
```

My call to the link method is:

```javascript
text = Autolinker.link(
                        message.text, 
                        {
                            twitter: false,
                            replaceFn : function(autolinker, match) {
                                var tag = autolinker.getTagBuilder().build(match);  
                                tag.setInnerHtml(match.getMatchedText());
                                return tag; 
                            }
                        }
                   );
```

**Comment by gregjacobs** [comment]
Hey, which version of Autolinker are you using? That text links okay for me with v0.20.0.

Going to close this issue for now, but feel free to reopen if you're still having a problem.

**Comment by asiminiceanu** [comment]
Hi Greg,

I was using 0.18.1. I will give 0.20.0 a try today.

**Comment by asiminiceanu** [comment]
So I have tried 0.21.0 but still the result is NOK.

```
<a href="enterprisehttp://blog.kodiakptt.com" target="_blank">enterprisehttp://blog.kodiakptt.com</a>
```
The protocol enterprisehttp is not valid. Maybe it would be better to be able to define what protocols this lib should support.
