### ISSUE TITLE
Trouble with Autolinker while using webpack

### ISSUE THREAD

**Issue by Dharmoslap** [gregjacobs/Autolinker.js#124]
I'm bundling my javascript modules using `webpack-dev-middleware` and `webpack-hot-middleware`, exactly like here https://github.com/gaearon/react-transform-boilerplate
But I have a trouble with Autolinker (https://github.com/gregjacobs/Autolinker.js) package.
See below.
![screen shot 2015-10-05 at 18 02 33](https://cloud.githubusercontent.com/assets/3543614/10286395/d1d2c5ba-6b8d-11e5-85bc-e34ca7215383.png)

**Comment by gregjacobs** [comment]
Hmm, not sure why there is `undefined` on line 17 instead of the keyword `this`. Does webpack do some transformations to source files before the page serves them?

**Comment by LeZuse** [comment]
Duplicate of https://github.com/gregjacobs/Autolinker.js/issues/86
