### ISSUE TITLE
Why is B.Sc. converted to url link

### ISSUE THREAD

**Issue by madhur** [gregjacobs/Autolinker.js#125]
I am entering the string `B.Sc.`  as the string and this string is converted to http:// form. `B.Sc.` is one of the educational degrees in india. How can I prevent this?

**Comment by simison** [comment]
`sc` is a top-level domain (ccTLD) for Seychelles, listed here: https://github.com/gregjacobs/Autolinker.js/blob/master/src/matchParser/MatchParser.js#L112

https://en.wikipedia.org/wiki/.sc

You could create a custom replacement function for URLs and ignore that TLD: https://github.com/gregjacobs/Autolinker.js#custom-replacement-function

**Comment by madhur** [comment]
:+1:
