### ISSUE TITLE
phone number format

### ISSUE THREAD

**Issue by martingg88** [gregjacobs/Autolinker.js#128]
does it handle the following format?

+60128183555

**Comment by simison** [comment]
Nope. :-/

http://rubular.com/r/Ljut8sn7oS

https://github.com/gregjacobs/Autolinker.js/blob/master/src/matchParser/MatchParser.js#L108

**Comment by martingg88** [comment]
can i add custom matcherRegex  to handle most of the phone format from the world?

**Comment by gregjacobs** [comment]
Hey @martingg88. If you can provide that regex, would be happy to include it with the core library!

**Comment by olafleur** [comment]
In the last version, this format is handled.

**Comment by tangkunyin** [comment]
@gregjacobs Does `matcherRegex ` not support external definition?
