### ISSUE TITLE
Umlauts and autolinker

### ISSUE THREAD

**Issue by dmr** [gregjacobs/Autolinker.js#133]
Is autolinker linking Umlaute correctly?

```
var t = 'www.bü.de';
console.info(t, autolinker.link(t));


www.büro.de --> <a href="http://www.b">www.b</a>üro.de
```

Anybody else with these problems?

**Comment by eteeselink** [comment]
Yep, I had it with this beautiful URL: https://www.google.nl/maps/place/Jastrzębie+Zdrój,+Polen/@50.2382659,18.0383159,8z/data=!4m2!3m1!1s0x4711531967e6fff9:0x2d46bb7bab386866

**Comment by eteeselink** [comment]
I might manage to submit a pull request for this btw

**Comment by dmr** [comment]
Cool!

**Comment by simison** [comment]
Dublicate #89

**Comment by gregjacobs** [comment]
Finally added support for all international chars!
