### ISSUE TITLE
Quick question about twitter handles

### ISSUE THREAD

**Issue by nitinthewiz** [gregjacobs/Autolinker.js#134]
I'm just wondering this out loud - the library links twitter handles, but does it actually verify that the twitter account exists?

I don't see that actually happening in the code, so I'm curious.

**Comment by gregjacobs** [comment]
Hey Nitin. No, the code does not make any effort to confirm with Twitter if the usernames exist. That would involve an async network request to Twitter's server, and that's just not really within the scope of what Autolinker is designed to do.

If you need something like this behavior though, I might be able to help your write it with some post-processing and DOM manipulation

**Comment by nitinthewiz** [comment]
@gregjacobs thanks for confirming. No, I don't think there's any great benefit to writing fresh code to solve that problem. 

I have a very small liveblog implementation that I slowly keep extending. My current workflow involves making sure the twitter handle exists and then writing/copying it to my creation web form. That form submits and sends posts to my liveblog, twitter and app.net accounts. Extending that functionality is just a past time. :smile: 

I think such a library does exist out there and I've seen it before. Some day I'll look for it and integrate it into my 'create' form.
