### ISSUE TITLE
Hashtags don't work

### ISSUE THREAD

**Issue by noodlebreak** [gregjacobs/Autolinker.js#135]
I'm doing this:

    // Parse to find links and make links clickable
    message_text = Autolinker.link(message_text, email=true, twitter=true, hashtag='twitter')

And it very beautifully parses links (google.com or http://google.com etc), twitter handles, email addresses (thank you!), but it fails to parse hashtags.

Am I doing something wrong?

**Comment by simison** [comment]
Duplicate #115

**Comment by simison** [comment]
Would you have an example `message_text` to demonstrate the issue?

**Comment by noodlebreak** [comment]
They're not Cyrillic symbols, as in #115.
They're simply English words. I tried out a bunch like #StarWars, #Yoda, #Python. None worked.

**Comment by gregjacobs** [comment]
Hey, if you're still having this issue (2 months later..), you're not calling the method correctly. Should be:

```
message_text = Autolinker.link( message_text, { email: true, twitter: true, hashtag: 'twitter' } );
```

Unless you're using CoffeeScript or some other transpiler in which case I have no idea how that works :)
