### ISSUE TITLE
Live demo?

### ISSUE THREAD

**Issue by dandv** [gregjacobs/Autolinker.js#138]
Would be [nice](https://github.com/ljosa/urlize.js/issues/21) to have one, like http://soapbox.github.io/linkifyjs/ or http://ali-saleem.github.io/anchorme.js/

**Comment by gregjacobs** [comment]
Good idea. Will do

**Comment by noway421** [comment]
It doesn't support idn, for anyone who's wondering.

**Comment by gregjacobs** [comment]
@noway421 it does now :)

**Comment by gregjacobs** [comment]
Added initial live example. Let me know what you think, and any improvements that could be made.

http://gregjacobs.github.io/Autolinker.js/examples/live-example/
