### ISSUE TITLE
Autolinker.js doesn't recognize local ips

### ISSUE THREAD

**Issue by Thatkookooguy** [gregjacobs/Autolinker.js#148]
When I write a local web address as: `http://10.0.0.108:9000/`, `Autolinker.js` doesn't recognize it as a url.

Is there an option I missed to enable this or is this just not implemented as a rule?

thanks

**Comment by gregjacobs** [comment]
Hey, currently no option for that, but definitely something to add. Feel like making a PR? :)

**Comment by Thatkookooguy** [comment]
sure! I'll try and work on this and add a PR :+1:

**Comment by gregjacobs** [comment]
Support added in v0.28.0
