### ISSUE TITLE
Consider adding option to set rel='noopener' or rel='noreferrer'

### ISSUE THREAD

**Issue by alexpelan** [gregjacobs/Autolinker.js#149]
Since autolinker defaults to opening up links in a new window using target=_blank, many of your users are likely affected by this vulnerability: https://mathiasbynens.github.io/rel-noopener/

Consider adding an option to set rel='noopener' and rel='noreferrer', or do it by default.

**Comment by alexpelan** [comment]
For now, something like this can be used as a workaround, where $("a") is scoped to whichever links you actually want to change:

    $("a").attr("rel", "noopener noreferrer");

**Comment by gregjacobs** [comment]
Hey, thanks for this, and thanks for the PR. Didn't even know about this potential type of attack!

**Comment by theoutlander** [comment]
This is interesting. However, it breaks links for telephones. Those will not launch skype or other handlers when noopener is set. How can we address that?

**Comment by alexpelan** [comment]
I don't have bandwidth to make another PR right now, but it's a pretty simple fix, just check if matchType !== "phone" before doing this: https://github.com/gregjacobs/Autolinker.js/blob/master/src/AnchorTagBuilder.js#L94

Good fix for someone new to OSS or new to the project
