### ISSUE TITLE
#link freezes when parsing text with < character

### ISSUE THREAD

**Issue by mlolson** [gregjacobs/Autolinker.js#157]
The html parse regex freezes when a "<" character is in the text.

[repro script](https://gist.github.com/mlolson/8caa69beb2df50f882003e2719c46e03)

[Looks like the thread freezes here](https://github.com/gregjacobs/Autolinker.js/blob/master/src/Autolinker.js#L439)

Using Autolinker v0.26.0, node 0.12.7

I think the problem arises when there is a "<" followed by a large amount of text, as in the example provided.

**Comment by gregjacobs** [comment]
Hey, I got to the bottom of this, thanks for the example string. I added it as a test, and definitely works in node 5 and Chrome. Try out the new version I just published: 0.27.0

Let me know if you're still having trouble in node 0.12
