### ISSUE TITLE
URLs preceded with text are not linked correctly

### ISSUE THREAD

**Issue by AlvaroIHS** [gregjacobs/Autolinker.js#159]
asdasda<a href="http://example.com/" target="_blank">http://example.com</a> will link like:

`<a href="asdasdahttp://example.com/" target="_blank">asdasdahttp://example.com</a>`

It should link:

`asdasda<a href="http://example.com/" target="_blank">http://example.com</a>`

**Comment by jasongrishkoff** [comment]
Running into the same issue.

**Comment by gregjacobs** [comment]
Hey guys. So autolinker tries to link many schemes other than just `http:` or `https:`. That's why it is linking "too much" in this case.

What are some inputs from users that you are getting which exhibit this problem though?

**Comment by jasongrishkoff** [comment]
Something as simple as "hahahttp://www.submithub.com" was getting messed up.  I'm using a bit of a hack solution to get around it:

`var text = "hahahttp://www.indieshuffle.com"
var text = text.replace("http"," http") //forcing a space to the start
var text = Autolinker.link(text)`

Seems to pretty much do the trick.

**Comment by gregjacobs** [comment]
Ok, interesting. I'm thinking maybe the code should make an exception for this particular case then. If it finds http or https at the end of the scheme string, it should assume that the scheme is http or https and remove anything that comes before it. 

Will work on this when I get a chance maybe next weekend, or other pull requests are definitely welcome!

**Comment by ivpusic** [comment]
@gregjacobs any updates here?

**Comment by olafleur** [comment]
@ivpusic Not for the moment, but you are more than welcome to submit a pull request! :)

**Comment by gregjacobs** [comment]
Going through old issues, and working on this now!

**Comment by gregjacobs** [comment]
Fixed with #275
