### ISSUE TITLE
BUG: Emoji text turns browser eating 100% CPU

### ISSUE THREAD

**Issue by marcalj** [gregjacobs/Autolinker.js#165]
```Autolinker.link('-Que estupendos nos vemos <3#lapeorfoto #despedida2016 #dehoyoenhoyo #rabbit 😂😂')```

BOOM :(

**Comment by gregjacobs** [comment]
Hey, thanks for this example input string. I figured out the issue (weird regex issue in Chrome, while Node was working fine).

Fixed in 0.27.0

**Comment by marcalj** [comment]
Great! Thanks!
