### ISSUE TITLE
On parse, a specific string hangs / crashes the browser

### ISSUE THREAD

**Issue by arjenfvellinga** [gregjacobs/Autolinker.js#172]
We use your library 0.27.0 to parse incoming emails on links. On a specific email the parser hangs and eventually crashes the browser (Chrome in my experiment). You could reproduce the problem on your demo page https://gregjacobs.github.io/Autolinker.js/examples/live-example/ with the following excerpt:

`<Office%20days:%20Tue.%20&%20Wed.%20(till%2015:30%20hr),%20Thu.%20(till%2017:30%20hr),%20Fri.%20(till%2012:30%20hr).%3c/a%3e%3cbr%3e%3c/td%3e%3ctd%20style=>`

I admit it is a weird string, but it came directly from a customer email.

**Comment by mibanez** [comment]
I have a similar problem with this input from Facebook ```<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3```

I also noticed that this crashes in Node.js v4.5.0 and Chrome, but not in Safari

**Comment by olafleur** [comment]
Was able to reproduce in both cases.

**Comment by gregjacobs** [comment]
Fixed in 1.3.0

**Comment by olafleur** [comment]
Good job @gregjacobs ! :)

**Comment by arjenfvellinga** [comment]
Indeed, thanks!
