### ISSUE TITLE
URL parsing doesn't take into account local URLs

### ISSUE THREAD

**Issue by marceloschmidt** [gregjacobs/Autolinker.js#180]
Local URLs could contain a number as last part of base URL. Eg.: http://localhost.local001/test

Ref.: https://github.com/RocketChat/Rocket.Chat/issues/4911

**Comment by olafleur** [comment]
Oh, I did not know that you could have number in the end of an URL.
Will try to work on that if I have time this week-end.

As a reference, here is a link that explains how a number could be contained in a TLD.

Thanks !

**Comment by olafleur** [comment]
In fact, here is a list of valid TLD, as of Nov. 11 : 
http://data.iana.org/TLD/tlds-alpha-by-domain.txt

**Comment by olafleur** [comment]
So, from what I understand, this is a request to allow pretty much every string as last part of URL.
The code was built with valid TLDs in mind.

@gregjacobs : should we allow any string of numbers and letters or stay with valid TLDs ? What do you think?

**Comment by gregjacobs** [comment]
Hmm, good question. I think that if the "http://" exists, we should probably accept it. But if it's just the text "localhost.local001" without the http, then not. What do you think?

**Comment by olafleur** [comment]
Seems like a good compromise for me. Will be working on this in the Days to come. :)

**Comment by gregjacobs** [comment]
Fixed in 1.3.2

**Comment by marceloschmidt** [comment]
You guys rock! Thank you!
