### ISSUE TITLE
v1.3.1 compatibility issue with IE7 and IE8

### ISSUE THREAD

**Issue by ilyakanevsky** [gregjacobs/Autolinker.js#188]
The new v1.3.1+ utilizes the forEach() function, which is not compatible with IE7 and IE8 since those browsers don't have that function. Would be great for IE7 and IE8 compatibility version.

**Comment by olafleur** [comment]
I don't think support for IE7 and/or IE8 is planned.

**Comment by ilyakanevsky** [comment]
#144 was fixed about a half year ago. Fix is simple.

**Comment by olafleur** [comment]
Oh ok. Then feel free to submit a pull request. :)

**Comment by gregjacobs** [comment]
Ugh, sorry about that. I'm so used to using forEach() in my day-to-day these days that I forgot! Feel free to submit a PR or I'll take a look as soon as I get a chance

**Comment by olafleur** [comment]
I've submitted a fix for the instance of forEach that I could find in the library. There are other instances, but it is in tests and examples, so it should not be a problem if you use the library in itself.
Could you tell me if it looks fine on your side @ilyakanevsky ?
