### ISSUE TITLE
Support for the Phone number extensions

### ISSUE THREAD

**Issue by pratyushtewari** [gregjacobs/Autolinker.js#189]
Hi @gregjacobs,
This library is awesome.

Is there any way to enhance this and accept the phone numbers with extensions with comma-separated values.

eg: 1-800-444-1234,10226420346# should convert to `tel:18004441234,10226420346#` 

Thanks,
Pratyush

**Comment by gregjacobs** [comment]
Hey Pratyush. Glad the library is helping you out! I'm not to familiar with the tel: scheme. Is that the correct way for a phone number extension to be put into a url? (With the comma?) Will mobile phones call the right number, and enter the extension for the user at the right time?

**Comment by pratyushtewari** [comment]
@gregjacobs Sorry got caught up.

Yes the   `<a href='tel:18004103523,10258671249#'>Click here to dial</a>` works on phone as well. And with Mac and windows as well.

Here is a test page:
[http://ptewari.com/numbertest/](numbertestl)

Let me know if that works for you.

**Comment by pratyushtewari** [comment]
Hi @gregjacobs,
Did you get any chance to look into this enhancement?

Thanks,
Pratyush

**Comment by pratyushtewari** [comment]
I was testing the following regex that seems to be working for me in [Phone.js](https://github.com/gregjacobs/Autolinker.js/blob/master/src/matcher/Phone.js)

`/(?:(\+)?\d{1,3}[-\040.])?\(?\d{3}\)?[-\040.]?\d{3}[-\040.]\d{4},[0-9]*#/g`

**Comment by pratyushtewari** [comment]
I think I achieved this by using the grouping.
Attached here is a part of Phone.js

Let me know what you think

[Phone.js.zip](https://github.com/gregjacobs/Autolinker.js/files/733293/Phone.js.zip)

**Comment by pratyushtewari** [comment]
Sent you a pull request #192

**Comment by pratyushtewari** [comment]
I think I got it. 

Sent you a pull req #193
