### ISSUE TITLE
URL matcher doesn't recognize new national TLDs like .рф

### ISSUE THREAD

**Issue by tsx** [gregjacobs/Autolinker.js#200]
Autolinker doesn't recognize valid urls like http://россия.рф or their punicode equivalent http://xn--d1acufc.xn--p1ai.

(GitHub doesn't get Cyrillic one either 😐)

It seems like a list of common TLDs is used in https://github.com/gregjacobs/Autolinker.js/blob/1.4.1/src/RegexLib.js#L57

I'd suggest either using a permissive alphanumeric unicode regex like /[-\w]{2,63}/u or importing the [official list](http://data.iana.org/TLD/tlds-alpha-by-domain.txt) in its entirety, and also providing unicode equivalents to punicode TLDs like xn--...

**Comment by olafleur** [comment]
Good point ! You're more than welcome to submit a pull request if you want ! :)
