### ISSUE TITLE
Browser freezes / 100% CPU when parsing some invalid HTML

### ISSUE THREAD

**Issue by philfreo** [gregjacobs/Autolinker.js#204]
Similar to #54, pasting this (invalid) HTML into the [demo site](http://gregjacobs.github.io/Autolinker.js/examples/live-example/) or into `Autolinker.link(bad_string_here)` freezes the browser.

`<img src="http://example.com/Foo" border-radius:2px;moz-border-radius:2px;khtml-border-radius:2px;o-border-radius:2px;webkit-border-radius:2px;ms-border-radius:="" 2px; "=" " class=" ">`

**Comment by gregjacobs** [comment]
Dang, just when I thought I had solved all of the ReDoS issues! 

Will take a look

**Comment by MortenHofft** [comment]
This might also explain my issue. I see this freeze, but eventually finish. It takes a long time though.

> All Lepidoptera and Coleoptera were identified to species, counted and written into a data file, published here. The final data set was subjected to a thorough quality check, and the few records (<20 individual records) in Lepidoptera that could not be accounted for by comparison of collection periods were discarded. We excluded the first (1992) and the last year (2009) of the data set to minimize start-up effects (operating the trap in a standardized manner comparable to the remainder of the study period) and influence from alteration of the local habitat in 2009. Furthermore, in 1992 and 2009 the trap was not active in the entire season. To account for variation in sampling intervals, we grouped the data set into standardized 10-day periods the first starting on 1st of January (Julian Day 1) and the last period ending on December 26 (Julian Day 360). The 10-day interval is slightly longer than the mean sampling interval of 7 days. Furthermore, all handling and identification of material was carried out consistently throughout the entire period by the same group of researchers.

Sorry for the long paragraph - i tried to isolate what it was, but couldn't find any one snippet that did it. Maybe just the length of it?

**Comment by gregjacobs** [comment]
Hey @MortenHofft. This issue has generally come up in the past with anything that starts with a `<` (my guess is the `<20`). Probably causing the regular expression that parses HTML to go exponential in attempting to match an HTML tag. The length of the input text shouldn't matter too much aside from that. 

I might just have to bite the bullet and write a non-regular expression version of the html parser.

**Comment by philfreo** [comment]
@gregjacobs any update here?

**Comment by gregjacobs** [comment]
Hey @philfreo, @caseywebdev came up with a solution using atomic grouping to prevent catastrophic backtracking in the regex. Give it a try now!

**Comment by philfreo** [comment]
Thanks! It works well. That @caseywebdev is 💯!
