### ISSUE TITLE
double dots in querystring

### ISSUE THREAD

**Issue by giammin** [gregjacobs/Autolinker.js#215]
link with double dots query string (key or value) are not recognized.
EX:
https://www.google.it/search?q=autolink.js&oq=autolink.js&aqs=chrome..69i57j0l4.5161j0j7&sourceid=chrome&ie=UTF-8

or 

https://www.google.it/search?q=autolink.js&oq=autolink.js&aqs=chrome..69i57j0l4.5161j0j7&sourceid=chrome&ie=UTF-8#newwindow=1&q=autolink.js

those link are from chrome address bar searches

**Comment by asssaf** [comment]
this happens in the path too, not just the query sting

**Comment by aprilandjan** [comment]
This also happened in gitlab branch compare url such as <https://gitlab.example.com/space/repo/compare/master...develop>

**Comment by StevenYuysy** [comment]
fix in https://github.com/gregjacobs/Autolinker.js/pull/225
