### ISSUE TITLE
Bug in autolink

### ISSUE THREAD

**Issue by shubham-agrawal** [gregjacobs/Autolinker.js#218]
http://search%3Fp%5BsubCategory%5D%3Dpen+drive%26f%5BMemory%5D%3D8%2520GB

should either highlight the complete url as link or nothing at all as it is not a valid url
but is only highlights http://search

**Comment by gregjacobs** [comment]
Not sure how that's a valid URL at all (it's not, really), but seems GitHub's naïve autolinking implementation thinks it's okay. However, notice that clicking on that link in your browser brings you nowhere.

I'm going to say this is not something we want to accept as a URL in Autolinker.
