### ISSUE TITLE
Skipping html tags

### ISSUE THREAD

**Issue by sorayasiahpolo** [gregjacobs/Autolinker.js#223]
Basically, if the user enters `<a href="www.google.com">google</a>`, the Autolinker produces link which is not what I want. I expect to see `<a href="www.google.com">google</a>` as a plain text. Is there a work around this issue?

**Comment by gregjacobs** [comment]
Hey @sorayasiahpolo. So `<a href="www.google.com">google</a>` is HTML, which would mean it wouldn't be shown as plain text when you output it to your HTML document (it would be shown as a link). This will be the result regardless of if you send that string through Autolinker or not.

If you want to see that as plain text on a browser, you need to convert the `<` and `>` characters to their corresponding html entities `&lt;` and `&gt;`:

```html
&lt;a href="www.google.com"&gt;google&lt;/a&gt;
```

Unless I'm not understanding your issue exactly?

**Comment by sorayasiahpolo** [comment]
Thanks @gregjacobs :)

**Comment by gregjacobs** [comment]
Np @sorayasiahpolo - let me know of any other issues!
