### ISSUE TITLE
Closing square bracket included in url

### ISSUE THREAD

**Issue by Kequc** [gregjacobs/Autolinker.js#228]
If there are square brackets the library includes them as part of the url.

`[cat http://example.com] => [cat <a href="http://example.com]">http://example.com]</a>`
`(cat http://example.com) => (cat <a href="http://example.com">http://example.com</a>)`

**Comment by Kequc** [comment]
If you are not thinking about cats it's the same issue.

`[http://example.com] => [<a href="http://example.com]">http://example.com]</a>`
`(http://example.com) => (<a href="http://example.com">http://example.com</a>)`

**Comment by gregjacobs** [comment]
Fixed in v3.0.2
