### ISSUE TITLE
Need additional customize tag

### ISSUE THREAD

**Issue by supercreator** [gregjacobs/Autolinker.js#229]
Need the customize tag. For example *123456433234 then autolink to the url that we can assign. We can add the others too: ~987654321. The auto video embed is also prefered. Youtube url, facebook url, twitch url, vimeo url for example. I think this plugin will be great. Thank you Gregory for your good code.

**Comment by gregjacobs** [comment]
Hi @supercreator. Somehow I missed you adding this issue :X Many apologies! 

If it still helps, you can use the `replaceFn` option to customize the tag that is created to exactly how you want it. There is an example in the readme here: https://github.com/gregjacobs/Autolinker.js#custom-replacement-function 

Best,
Greg
