### ISSUE TITLE
Warn in README about sanitizing input first

### ISSUE THREAD

**Issue by ustun** [gregjacobs/Autolinker.js#23]
If the user doesn't sanitize the input before passing to Autolinker, and then she feeds it to the DOM in that form, it will be a security issue. This is probably obvious for most, but still needs to be mentioned I think. 

https://code.google.com/p/google-caja/wiki/JsHtmlSanitizer Caja sanitizer could be linked from there as an example.

**Comment by cooervo** [comment]
Does this provide protection against XSS?
1. Sanitize html 
2. Use autolinker

**Comment by gregjacobs** [comment]
Not sure actually. I'm not too familiar with xss other than to make sure users can't add <script> tags. Maybe the other way around though? Running Autolinker first and then sanitizing should cover you (as long as your sanitizer doesn't remove other html tags as well!)
