### ISSUE TITLE
Emoji IDNs should be hyperlinked

### ISSUE THREAD

**Issue by meyt** [gregjacobs/Autolinker.js#238]
E.g. http://🍕💩.ws - GitHub does it correctly!

p.s: same as https://github.com/alexcorvi/anchorme.js/issues/1

**Comment by marceloschmidt** [comment]
Yes, this would be a great addition. Do you need any help with that?

**Comment by gregjacobs** [comment]
Pull requests always welcome! 

But, qq: is that actually a valid domain name? I think GitHub's heuristic is to just link anything it finds after http://, including wildly invalid domain hosts like http://%20%DF

**Comment by gregjacobs** [comment]
Or maybe I'm wrong about that since that didn't get linked :D

**Comment by gregjacobs** [comment]
Err, I guess that is a valid domain name :) Do we need to change it to punycode for the url itself? (Sorry I'm on a phone right now or else I would check all these things out myself :))

**Comment by marceloschmidt** [comment]
If you encodeURI the URL, then you can just add '%' to the regex. 
`http://🍕💩.ws` becomes `http://%F0%9F%8D%95%F0%9F%92%A9.ws`

**Comment by gregjacobs** [comment]
Fixed with #276
