### ISSUE TITLE
Issue with matching dakuten on katakana in URL

### ISSUE THREAD

**Issue by zdhickman** [gregjacobs/Autolinker.js#248]
To reproduce, see these two examples:

https://website.com/file/text-ボ.pdf - with dakuten
https://website.com/file/text-ホ.pdf - without dakuten

Using the [live example](http://greg-jacobs.com/Autolinker.js/examples/live-example/):

![image](https://user-images.githubusercontent.com/2453653/46764533-ab955f80-ccaa-11e8-8b14-e5a3756ef75f.png)

**Comment by zdhickman** [comment]
Quick follow-up here - did some investigating and found that the issue seems to be browser/OS specific. I put up [a StackOverflow question](https://stackoverflow.com/questions/52750361/why-does-regex-matching-with-special-unicode-characters-return-different-results) with all the details.

So, this issue doesn't seem to have anything to do with your library, except for the fact that it's using `RegExp`...I'm happy to close this out, but maybe there's some workaround we can find here.

**Comment by gregjacobs** [comment]
Hey @zdhickman, this is really an interesting issue. Thanks for reporting, and great analysis in your stackoverflow! 

I can't say that I'm much of a unicode expert, so I'm not sure exactly what to do :X  The current regex that matches "letter" characters comes directly from XRegExp (http://xregexp.com/v/3.0.0/unicode-categories.js, look for: `alias: 'Letter'`)

Would love to find a workaround of course though. I would say maybe one option is to preprocess the string to combine letter + combining characters (just learned about this while researching this issue :)). Although it seems that letters may have any number of combining characters, so maybe the workaround is to just accept all of the combining characters in that regex. I'll see if I can reproduce your issue and if this second idea works

**Comment by zdhickman** [comment]
Thanks for the fix! LGTM in the live example.

**Comment by gregjacobs** [comment]
Awesome, glad to hear! Thanks for checking!
