### ISSUE TITLE
Several hashtags in a row

### ISSUE THREAD

**Issue by mksmtn** [gregjacobs/Autolinker.js#250]
For now If i write #hh#kk autolinker does not recognize the second hashtag. I consider this a bug.

**Comment by gregjacobs** [comment]
Hey @mksmtn. I'm just looking into this, and I don't know if this is valid actually. Neither Facebook nor Twitter allow two hashtags directly next to each other. Facebook links the first one but not the second, and Twitter links neither. 

Is this a valid scenario for some service? Let me know. I'm going to close this one out for now as I'm trying to go through the backlog of issues, but feel free to reopen or comment. Thanks!
