### ISSUE TITLE
Provide structured output for easier integration with React and other frameworks

### ISSUE THREAD

**Issue by harrislapiroff** [gregjacobs/Autolinker.js#251]
I read through this [conversation](https://github.com/gregjacobs/Autolinker.js/pull/140) and I still think there's some potential improvements that could be made. @gregjacobs, I'm not sure if anyone adequately explained to you during that conversation why processing to strings isn't React-friendly, but the short answer is that React _strongly_ discourages using HTML strings anywhere. In fact the officially documented way of using HTML strings is [designed to force you to notice that it's dangerous](https://reactjs.org/docs/dom-elements.html#dangerouslysetinnerhtml).

Instead, what one does in React is build up a tree of nested nodes, not unlike the DOM. These nodes can be React components, strings, or arrays. I agree with you that direct React integration may not belong in the Autolinker core, but it'd be nice if there was a separate method for extracting structured data about the processing that would make it easier to integrate with other post-linking needs. Maybe an `Autolinker.matches(string, options)` or `Autolinker.nodes(string, options)` method that outputs an array of match objects (or match objects and strings)?

In the meantime, I managed to write up what I think is a decently elegant workaround. It basically uses `replaceFn` as a loop during which I populate my real output variables. But it does bother me that `Autolinker.link` is going through all the computational effort to build a string, which I'm then discarding.

(If you're still not familiar with React, you'll notice I'm using JSX, which looks like HTML but actually compiles to a React component.)

```jsx
function autolinkReact(inputString) {
  let lastStringStart = 0 // A cursor for the match loop
  const reactNodes = []   // The destination for our react nodes
  Autolinker.link(inputString, {
    hashtag: 'twitter',
    mention: 'twitter',
    replaceFn: (match) => {
      // First add the string node between the last match and the current one
      reactNodes.push(string.slice(lastStringStart, match.offset))
      // Next, process the current match
      reactNodes.push(
        <a
          href={match.getAnchorHref()}
          rel="noopener noreferrer"
          target="_blank"
        >
          {match.getAnchorText()}
        </a>
      )
      // Update the cursor
      lastStringStart = match.offset + match.matchedText.length
    }
  })
  // Add last stringy bit, if any
  reactNodes.push(decodedString.slice(lastStringStart))
  return reactNodes
}
```

(I actually have a more complicated wrapper that traverses an entire React component subtree looking for strings to autolink, but that didn't seem fully relevant here.)

This is a great library, though, and still saved me hours of work, so much thanks! Very grateful.

**Comment by gregjacobs** [comment]
Hey @harrislapiroff. I think you're looking for the [parse](http://greg-jacobs.com/Autolinker.js/api/#!/api/Autolinker-static-method-parse) method :) Returns the array of [Match](http://greg-jacobs.com/Autolinker.js/api/#!/api/Autolinker.match.Match) objects without actually processing the underlying string. I'll add a link to that method in the main readme since I guess it's a bit obscure in the API docs.

Glad Autolinker has saved you time!

**Comment by harrislapiroff** [comment]
@gregjacobs I can't believe I missed that. Thanks for your response. :)
