### ISSUE TITLE
long data URI of font face in style tag cause browser freezing

### ISSUE THREAD

**Issue by examan** [gregjacobs/Autolinker.js#252]
If style element contains long data URI, Autolinker will freeze at matcherRegex.exec.

`@font-face {
  font-family: 'Work Sans';
  src: local('Work Sans'), local('WorkSans-Regular'), url(data:font/woff;base64,............................................................);
}`

Style element should be skipped parsing to prevent this issue.

**Comment by examan** [comment]
#253

**Comment by gregjacobs** [comment]
Merged #253 - thanks!
