### ISSUE TITLE
error TS1039: Initializers are not allowed in ambient contexts.

### ISSUE THREAD

**Issue by WarayAmine** [gregjacobs/Autolinker.js#262]
Hi, i am trying to use the autolinker for angular 6, but i am receiving this error : 
`ERROR in node_modules/autolinker/dist/commonjs/autolinker.d.ts(130,31): error TS1039: Initializers are not allowed in ambient contexts.
node_modules/autolinker/dist/commonjs/autolinker.d.ts(227,24): error TS1039: Initializers are not allowed in ambient contex` when doing the ng build --prod.
In that autolinker.d.ts file, the error is here `static readonly version = "3.0.0";`

I am on Typescript 2.9.2 and Autolinker 3.0.0.
If someone knows what should i do, i'll appreciate it. Thanks.

**Comment by gregjacobs** [comment]
Hey @WarayAmine. I just tried importing Autolinker into an Angular 7 project and it both served and built in prod mode okay. 

How are you importing Autolinker? I'm using the syntax:

```js
import Autolinker from 'autolinker';
```

Let me know if this is still an issue for you. I'm going to close this for now, but feel free to reopen

**Comment by michahell** [comment]
for me, the above does not work. I'm getting the following error on compile:
`ERROR in src/../../some.component.ts(9,8): error TS1192: Module '"autolinker"' has no default export.`

**Comment by ypkkhatri** [comment]
Hi, that issue still occurred with `angular@6`, I have also tried older version of `autolinker@2.0.0` but error still there, below is the error log of it:

```
Failed to compile.

node_modules/autolinker/dist/commonjs/autolinker.d.ts(130,31): error TS1039: Initializers are not allowed in ambient contexts.
node_modules/autolinker/dist/commonjs/autolinker.d.ts(227,24): error TS1039: Initializers are not allowed in ambient contexts.
```
