### ISSUE TITLE
Option to include `mailto:` scheme in matched email URL

### ISSUE THREAD

**Issue by adamdavidcole** [gregjacobs/Autolinker.js#272]
Currently, if you give autolinker a full email URL like `mailto:example@gmail.com`, only the `example@gmail.com` becomes linked. 

I’d propose adding an option or changing the default behavior to match on the entire link including the `mailto:` scheme so that all of `mailto:example@gmail.com` becomes a link. 

This is the standard behavior across web based text editors I’ve tested on including Google Docs, Microsoft One Drive and Dropbox Paper. 

Thanks for considering!

**Comment by gregjacobs** [comment]
Hey @adamdavidcole, that's a great suggestion, and entirely possible to do

**Comment by adamdavidcole** [comment]
Fixed in the newest release (v3.10.0) 🎉
