### ISSUE TITLE
browser field priority

### ISSUE THREAD

**Issue by TrySound** [gregjacobs/Autolinker.js#279]
Browser field specified here has bigger priority for bundlers than `module` field.
https://github.com/gregjacobs/Autolinker.js/blob/master/package.json#L8

You should not use it to distribute umd bundles. Here's more correct usage if it's required.
https://github.com/styled-components/styled-components/blob/master/packages/styled-components/package.json#L9-L12

**Comment by gregjacobs** [comment]
Merged your PR - thanks!
