### ISSUE TITLE
Version not being incremented

### ISSUE THREAD

**Issue by Technetium1** [gregjacobs/Autolinker.js#280]
Autolinker.min.js & Autolinker.js have a version number that is not being incremented. [The last commit was a release tagged v3.10.0](https://github.com/gregjacobs/Autolinker.js/commit/96f86a9b0a4bad7584389e568a37b7acb278da2b)

https://github.com/gregjacobs/Autolinker.js/blob/96f86a9b0a4bad7584389e568a37b7acb278da2b/dist/Autolinker.min.js#L3
https://github.com/gregjacobs/Autolinker.js/blob/96f86a9b0a4bad7584389e568a37b7acb278da2b/dist/Autolinker.js#L3

**Comment by gregjacobs** [comment]
Oops - thanks for the report! Will fix

**Comment by gregjacobs** [comment]
Fixed :)
