### ISSUE TITLE
Recognizing UUIDs as Phone numbers

### ISSUE THREAD

**Issue by BukkitPVP** [gregjacobs/Autolinker.js#285]
Autolinker recognizes UUIDs, such as 

> 27b94442-e2a2-40dd-ab55-4384702273e4

as phone numers.
The generated Code is:

`27b94442-e2a2-40dd-ab<a href="tel:554384702273" target="_blank" rel="noopener noreferrer">55-4384702273</a>e4`

I have no options or replace functions configured.

**Comment by gregjacobs** [comment]
This is now fixed in v4.0.0

Best,
Greg
