### ISSUE TITLE
IE11 and lower incompatability due to .find method being used

### ISSUE THREAD

**Issue by bkosborne** [gregjacobs/Autolinker.js#286]
A few months ago, this commit [introduced code](https://github.com/gregjacobs/Autolinker.js/commit/8acb9fe1573834c8e93b851df4d12988ba3fbd68#diff-82b20029bc72a465c97585b744fa885bR209) that uses the `.find` method on an array, which is not available in IE11 and under.

I think that's OK, it's not a commonly used browser, but can you please update the README / project homepage to indicate that it's used and that a [pollyfill](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find#Polyfill) is needed?

**Comment by gregjacobs** [comment]
Hey @bkosborne, thanks for reporting. Closing due to IE obsolescence 

Best,
Greg
