### ISSUE TITLE
Instagram mention parsing: string starting with @dot (@.) falsely recognised as IG mention

### ISSUE THREAD

**Issue by denova** [gregjacobs/Autolinker.js#288]
**Expected Behaviour**
IG usernames starting with (.) should be linkified

**Actual Behaviour**
IG usernames starting with (.) linkified when using `link` method.

**Screenshots**
IG:

![027c8ce65f](https://user-images.githubusercontent.com/1096682/65238375-33076780-dae5-11e9-83c4-dab19525b7e2.png)

Autolinker.js:

![45838324c2](https://user-images.githubusercontent.com/1096682/65238421-4c101880-dae5-11e9-8bf9-903d9f66aa45.png)

Didn't find docs about this but if you try to change you username using dot as the first symbol IG shows a error message.

#289 https://github.com/gregjacobs/Autolinker.js/issues/289

**Comment by denova** [comment]
hey guys, any updates here?

**Comment by Thr44** [comment]
this seems to have been resolved with 3.11.1
