### ISSUE TITLE
Instagram usernames followed by emoji should be linkified

### ISSUE THREAD

**Issue by Thr44** [gregjacobs/Autolinker.js#290]
**Expected Behaviour**
Instagram usernames added after an emoji should be linkified

😀@testing
🤔@testing

**Actual Behaviour**
Instagram usernames added after an emoji are not linkified, although on instagram they are

**Screenshots**

Instagram:

<img width="264" alt="Screenshot 2019-09-19 at 15 39 01" src="https://user-images.githubusercontent.com/1564286/65254098-a87a3480-daf3-11e9-900f-e70e0e4304f2.png">

Autolinker.js:

<img width="114" alt="Screenshot 2019-09-19 at 15 35 05" src="https://user-images.githubusercontent.com/1564286/65254099-a912cb00-daf3-11e9-9cff-4c2cf6dd272e.png">

**Comment by denova** [comment]
hey guys, any updates here?

**Comment by Thr44** [comment]
this seems to have been resolved with 3.11.1
