### ISSUE TITLE
Subdomains with underscores are not identified as links

### ISSUE THREAD

**Issue by haugstrup** [gregjacobs/Autolinker.js#299]
This is related to #277 in that it's an issue with `getDomainNameStr` in `regex-lib.ts`.

Subdomain names are treated pretty lax out in the wild. It's common to see subdomains with underscores, but autolinker won't identify these links.

For example: `http://_foo.example.com` will identify `foo.example.com` as the link. And `http://foo_bar.example.com` will identify two links (`http://foo` and `bar.example.com`).

@gregjacobs Do you have any general hints on how to target subdomains separately from the normal domain name in `getDomainNameStr`? I can make the changes and write tests, but I'm having some trouble parsing the current logic.

**Comment by pavholm** [comment]
Have the same problem

**Comment by Zheleznyak-F** [comment]
I have the same problem, links with underscores break into multiple parts.

 http://faq_for_users.domain.com -> converts into three parts, (`faq` and `users.domain.com` like links, and `_for_` like plain text);
 
 @gregjacobs Do you have any idea how to fix this problem? Maybe you can point out the origin of this problem.
 
 @haugstrup Have you invented a workaround? Can you share it?

**Comment by gregjacobs** [comment]
Hey guys, should have updated this issue years ago but this was fixed in v3.16 or so :)
