### ISSUE TITLE
Numeric URLs without TLD does not link

### ISSUE THREAD

**Issue by haugstrup** [gregjacobs/Autolinker.js#300]
`custom://q123` will link
`custom://1234` will **not** link

Granted this is a niche case, but it's not uncommon to see these types of URLs in intranets or other non-public tooling.

I think this is because `urlMatchDoesNotHaveAtLeastOneWordChar` uses `hasWordCharAfterProtocolRegex` which matches letters, but not numbers.

I believe this check should be loosened to allow numbers if the protocol includes `//`. For example `custom://123` should link while `custom:123` should not.

**Comment by gregjacobs** [comment]
Both now link properly in v4.0.0

Best,
Greg
