### ISSUE TITLE
Request: Please update gulp-header dependency version

### ISSUE THREAD

**Issue by alejandroclaro** [gregjacobs/Autolinker.js#301]
gulp-header version 1.7.1 produces a dependency on 'event-stream' package that has some known vulnerabilities. Even this is a devDepedency, it will be nice to remove this dependency and the warnings in audit tools.

Newer versions of gulp-header solves this issue.

**Comment by gregjacobs** [comment]
Hey, thanks for the heads up. Feel like opening a quick PR?

**Comment by gregjacobs** [comment]
Removed gulp from the build process and in turn removed gulp-header. Thanks for reporting!

Best,
Greg
