### ISSUE TITLE
Big drop in speed between 0.11.0 and 3.11.1

### ISSUE THREAD

**Issue by tomchadwin** [gregjacobs/Autolinker.js#314]
I use Autolinker in https://github.com/tomchadwin/qgis2web/. It was on 0.11.0 for years, but I updated recently in order to make use of the `truncate` option (https://github.com/tomchadwin/qgis2web/commit/c3d643da4eb5a3e8df02a11654be4e236ff3ad3e).

However, people are reporting a big drop in performance since this upgrade: https://github.com/tomchadwin/qgis2web/issues/852. Any explanation, or way in which we can improve performance?

**Comment by gregjacobs** [comment]
Hey @tomchadwin. Do you by any chance have some example data that I can test with?

**Comment by gregjacobs** [comment]
A lot of things have changed since 0.11.0 btw - would be very difficult to find a particular commit that might have affected performance :/ Might just have to track it down with some good example data that may be affecting performance

**Comment by tomchadwin** [comment]
Can @jukos or @cesarcorreo provide the testing data required to demonstrate this issue?

**Comment by cesarcorreo** [comment]
[time.zip](https://github.com/gregjacobs/Autolinker.js/files/4306236/time.zip)
I shared the file but unfortunately the hole project. It has more than 100 layers and some of them really heavy.
I tested this file with the followings time results to open layer properties:

1. This file in the hole project. QGIS 3.12.0. Windows 10 -> 5 sec
2. This file in the hole project. QGIS 3.10.2. Windows 10 -> 1 sec
3. This file in new project. No other layers. QGIS 3.12.0. Windows 10 -> 1 sec.

So, how to explain case 1 and 3????

**Comment by jukos** [comment]
[speed test qgis2web.zip](https://github.com/gregjacobs/Autolinker.js/files/4311130/speed.test.qgis2web.zip)


Hello,
I have also a fully test project.
Only with one big point layer with nearly 10.000 points.
Same result as with a project with many layers:
Slow with qgis2web 3.12
Fast with qgis2web 3.11
This is an easy test-project, but to much for 3.12......
I hope this could be help to find the issue.

Greetings, Jürgen

**Comment by gregjacobs** [comment]
Hey @tomchadwin, sorry for the delay. Working on this now though. 

I'm not sure how I might run Autolinker tests with files that are loaded into qgis2web. Do you by any chance have a long string or set of strings that you pass to Autolinker where you see long parse times?

Thanks,
Greg

**Comment by tomchadwin** [comment]
Hey, @jukos, @cesarcorreo, you did some tests back on the qgis2web issue. You did an export with the new version, which was slow, and dropped in the old version of Autolinker, and it sped up. What @gregjacobs needs is that slow output (he can drop in the old version of Autolinker himself). What you've uploaded here is QGIS stuff, which he doesn't deal with - Autolinker is a general web/JS library.

So, any chance you can do the simplest possible qgis2web export which demonstrated the slowdown, and upload *the output* here?

**Comment by jukos** [comment]
> So, any chance you can do the simplest possible qgis2web export which demonstrated the slowdown, and upload the output here?
[qgis2web_2020_04_06-14_00_27_329711.zip](https://github.com/gregjacobs/Autolinker.js/files/4438255/qgis2web_2020_04_06-14_00_27_329711.zip)

**Comment by gregjacobs** [comment]
Thanks @jukos, this is very helpful and I can work with this. I see load times of about 50sec on my machine with most of the time spent in scripting inside Autolinker. Investigating now

**Comment by gregjacobs** [comment]
Ok I see the issue. Each time `Autolinker.link()` is called, a new instance of `Autolinker` and all of its child objects are instantiated (which includes the relatively-expensive `RegExp` objects that Autolinker uses). Here's an example snippet from the generated code in the example that @jukos uploaded:

```js
function pop_chargingstations_1(feature, layer) {
    var popupContent = '<table>\
        <tr>\
            <td colspan="2">' + (feature.properties['fid'] !== null ? Autolinker.link(feature.properties['fid'].toLocaleString(), {truncate: {length: 30, location: 'smart'}}) : '') + '</td>\
        </tr>\
        <tr>\
            <td colspan="2">' + (feature.properties['id'] !== null ? Autolinker.link(feature.properties['id'].toLocaleString(), {truncate: {length: 30, location: 'smart'}}) : '') + '</td>\
        </tr>\
        <tr>\
            <td colspan="2">' + (feature.properties['@id'] !== null ? Autolinker.link(feature.properties['@id'].toLocaleString(), {truncate: {length: 30, location: 'smart'}}) : '') + '</td>\
        </tr>\
        // ...
```

The above `pop_chargingstations_1` function above is being called about 10,000 times in the example, which results in ~170,000 Autolinker instances which are temporarily created and then thrown away.

What you can do instead is instantiate Autolinker just once, and use that same Autolinker instance to link all of the different pieces of text. For example:

```js
// Single instance with options specified
var autolinker = new Autolinker({truncate: {length: 30, location: 'smart'}});

function pop_chargingstations_1(feature, layer) {
    var popupContent = '<table>\
        <tr>\
            <td colspan="2">' + (feature.properties['fid'] !== null ? autolinker.link(feature.properties['fid'].toLocaleString()) : '') + '</td>\
        </tr>\
        <tr>\
            <td colspan="2">' + (feature.properties['id'] !== null ? autolinker.link(feature.properties['id'].toLocaleString()) : '') + '</td>\
        </tr>\
        <tr>\
            <td colspan="2">' + (feature.properties['@id'] !== null ? autolinker.link(feature.properties['@id'].toLocaleString()) : '') + '</td>\
        </tr>\
        // ...
```

(note the lowercase `autolinker` on each of the `autolinker.link()` calls in this example, which all refer to the single instance of `Autolinker`)

I actually mention this performance thing very briefly in the readme in the "usage" section (https://github.com/gregjacobs/Autolinker.js#usage), but maybe I should make that more apparent!

> Note: if using the same options to autolink multiple pieces of html/text, it is slightly more efficient to create a single Autolinker instance, and run the link() method repeatedly (i.e. use the "class" form above).

Give this a try and let me know how it goes. When I made the above change, I saw the page's scripting time go from ~50 seconds to ~1 second

Best,
Greg

**Comment by tomchadwin** [comment]
Ah, this is fantastic! I'm so sorry to have missed that in the docs. Let me implement that as soon as I can in qgis2web, and then people can test. Thank you so much for investigating and setting me straight. Very much appreciated indeed!

**Comment by gregjacobs** [comment]
@tomchadwin Saw your comments in https://github.com/tomchadwin/qgis2web/issues/852 - glad it's solved! Let me know if you run across anything else :)

Best,
Greg
