### ISSUE TITLE
support ip address has no protocol

### ISSUE THREAD

**Issue by KotoriMinami** [gregjacobs/Autolinker.js#347]
hi,
When ip address has no protocol  is cannot work。

When the url like `http(s)://ip[:port]` is good
But when the url is `ip[:port]` no change

Because used in IM software, I think it should be a link

Please to look at ,Thx.

**Comment by gregjacobs** [comment]
IP addresses with no protocol now link with the `urls.ipV4Matches` option in v4.0.0 👍
