### ISSUE TITLE
doc/release v3.16.0 changelog missing

### ISSUE THREAD

**Issue by filipagh** [gregjacobs/Autolinker.js#385]
Hello
in npm you publish v3.16.0 but in github there is last releast 3.15.0

so there is no change log for 3.16.0 (diff 120+files changed)

or 3.16.0 is not stable ? 

please update doc/release as needed

**Comment by gregjacobs** [comment]
Hey @filipagh, thanks for pointing this out. Added a release for v3.16.0: https://github.com/gregjacobs/Autolinker.js/releases/tag/v3.16.0 

Best,
Greg
