### ISSUE TITLE
Add support for YouTube hashtags

### ISSUE THREAD

**Issue by ChunkyProgrammer** [gregjacobs/Autolinker.js#397]
The base url for a youtube hashtag is:

https://www.youtube.com/hashtag/

Example hashtag "minecraft"
https://www.youtube.com/hashtag/minecraft

**Comment by gregjacobs** [comment]
Hey, thanks for the info, and this would be a good addition. Unfortunately I don't know when I can get to this at this moment, but PRs definitely welcome!

**Comment by gregjacobs** [comment]
Added in v4.1.0. Thanks for reporting!
