### ISSUE TITLE
Add support for YouTube mentions

### ISSUE THREAD

**Issue by ChunkyProgrammer** [gregjacobs/Autolinker.js#398]
YouTube now supports @ mentions.

The base url for this is https://www.youtube.com/@

Ex for @ mrbeast
https://www.youtube.com/@mrbeast

**Comment by gregjacobs** [comment]
Hey, thanks for the info, and this would be a good addition. Unfortunately I don't know when I can get to this at this moment, but PRs definitely welcome!

**Comment by gregjacobs** [comment]
Added in v4.1.0. Thanks for reporting!
