### ISSUE TITLE
URL as value in key-value pair parsed only partially (and incorrectly)

### ISSUE THREAD

**Issue by threema-danilo** [gregjacobs/Autolinker.js#405]
The input string `FOO=https://example.com` is parsed as `FOO=https:[example.com](file://example.com)`:

- The `https://` part is not included
- The `//` part is stripped
- The `example.com` domain is linked, but using the `file://` protocol

**Comment by gregjacobs** [comment]
This is now fixed in 4.0.1. Thanks for reporting!
