### ISSUE TITLE
Ability to apply a 'title' attribute on truncated links

### ISSUE THREAD

**Issue by philfreo** [gregjacobs/Autolinker.js#41]
Minor thing, but it's good practice to add a `title` attribute to truncated text so the user can see the full untruncated version if they hover their mouseover it. So it'd be nice to be able to set the `title` attribute either of a) all links, or b) truncated links

Some of the ideas from https://github.com/gregjacobs/Autolinker.js/pull/17 would also make flexibility like this possible automatically

**Comment by olafleur** [comment]
Fixes in 1.4.0
