### ISSUE TITLE
In certain cases, links are not converted properly. (ex: `Link 2:https://nia.nexon.com`)

### ISSUE THREAD

**Issue by ynifamily3** [gregjacobs/Autolinker.js#413]
- `한글:https://nia.nexon.com`
  - Doesn't Works (parsed as ttps://nia.nexon.com)
-  `Link 2:https://nia.nexon.com`
   - Doesn't Works (parsed as ttps://nia.nexon.com)
- `a:nia.nexon.com`
  - It works (parsed as http://nia.nexon.com)

Can you help me with this situation?

![image](https://github.com/user-attachments/assets/0918bad6-bfa7-40c6-af39-5d63934df62c)

**Comment by gregjacobs** [comment]
This is now fixed in 4.0.1. Thanks for reporting!
