### ISSUE TITLE
Autolinker removes <br/> tags

### ISSUE THREAD

**Issue by Tallowman** [gregjacobs/Autolinker.js#46]
I retrieve text from the database, and apply nl2br() to convert the line breaks to br/ tags. Then, when I pass the text through autolinker, the br/  tags are removed.

**Comment by pratyushvidyarthi** [comment]
This issue is still not resolved, the <br> is still getting removed by the autolinker.

**Comment by pratyushvidyarthi** [comment]
This issue is still not resolved, the ---br-- tag is still getting removed by the autolinker.
