### ISSUE TITLE
AutoLinker.Link Fails with 100% CPU

### ISSUE THREAD

**Issue by sudpaw** [gregjacobs/Autolinker.js#54]
The link method freezes the browser if you use a string with: 
"Shai ist endlich in Deutschland! Und wir haben gute Nachrichten! <3 Alle, die den Shai-Rasierer kostenlos probieren, machen am Gewinnspiel eines Jahresvorrates Klingen mit. Den Rasierer bekommst Du kostenlos durch diesen Link: http://dorcoshai.de/pb1205ro, und dann machst Du am Gewinnspiel mit! „Gefällt mir“ klicken, wenn Du gern einen Jahresvorrat Shai haben möchtest. (Y)"

I have tried debugging the source, and it seems like the htmlRegex is the culprit.

**Comment by felquis** [comment]
My browser is freezing with 100% CPU right now... It happens in a content with hashtags and line break... 

the content contains
#hash1
#hash2
#hash3

`bla bla bla <3  #hash1↵#hash2↵#hash3`

I'm trying to get the DevTools timeline.. but the browser is so freezed that is doesn't works well.. So.. In my code I go until the snippet
```js
listOfContent.forEach(function (item, index) {
  listOfContent[index].content = Autolinker.link( list[index].content, autoLinkOptions )
})
```

my `autoLinkOptions` is:
```js 

var autoLinkOptions = {
  hashtag: 'twitter',
  replaceFn: function replaceHashTagLink(autolinker, match) {
    if (match.getType() === 'hashtag') {
      return '<a href="/resultado?q='+encodeURIComponent(match.matchedText)+'">' + match.matchedText + '</a>';
    }

    // remove link para twitters
    if (match.getType() === 'twitter') {
      return match.matchedText
    }

    // links completos usam target _blank
    if (match.getType() === 'url' && match.urlMatchType === 'scheme') {
      // URLs with scheme ex: http://teste.com ou sw://teste.com
      return '<a target="_blank" href="'+match.url+'">' + match.matchedText + '</a>';
    } else {
      // urls without scheme ex: teste.com
      return match.matchedText
    }
  }
}
```

Any idea how I can fix it?
