### ISSUE TITLE
Internationalized domain names are not linkified

### ISSUE THREAD

**Issue by perk11** [gregjacobs/Autolinker.js#57]
[Internationalized domain names](http://en.wikipedia.org/wiki/Internationalized_domain_name) are left as plain text. Tested both with node and browser.
Examples:
http://путин.рф/
xn--80aaalivalp6bdgclj4aa7q.xn--p1ai

**Comment by simison** [comment]
This package seems to be working for non-latin alphabet; https://github.com/regexps/url-regex

**Comment by puzrin** [comment]
@simison it's good to verify, but not good to autodetect. I'd recommend to look into test samples, used in all those packages. See also http://markdown-it.github.io/linkify-it/

**Comment by simison** [comment]
@puzrin actually this discussion should be continued here; #89

**Comment by gregjacobs** [comment]
Fixed in 0.24.0
