### ISSUE TITLE
phone numbers?

### ISSUE THREAD

**Issue by adjohnson916** [gregjacobs/Autolinker.js#59]
Converting phone numbers to `tel:` links. Any interest in this feature?

**Comment by sherbondy** [comment]
Shazam:
https://github.com/gregjacobs/Autolinker.js/pull/82

**Comment by gregjacobs** [comment]
Added in [v0.16.0](https://github.com/gregjacobs/Autolinker.js/releases/tag/0.16.0). Thanks @sherbondy, and sorry that I took so long!!
