### ISSUE TITLE
Strange protocol cut

### ISSUE THREAD

**Issue by puzrin** [gregjacobs/Autolinker.js#67]
```
 > require('autolinker').link('qqqqqqqqqqqq://hello.world')
'qqq<a href="qqqqqqqqq://hello.world" target="_blank">qqqqqqqqq://hello.world</a>'
```

Seems several errors at once.
1. I don't know, if autolinker should support alternate protocol schemas (skype, ftp, news, irc ...). If not - it should not make false positives on example above.
2. If yes, it should not break protocol name.

**Comment by Kagami** [comment]
Hi.
I see you guys here trying to filter danger protocols like "javascript" and "vbscript". Currently this is done by this code: `return ( uriScheme !== 'javascript:' && uriScheme !== 'vbscript:' );`.
I don't think this is a mature solution, I believe the only way to deal with scheme filtering is a whitelist (maybe customized by user). E.g. look at this scary big list: https://www.owasp.org/index.php/XSS_Filter_Evasion_Cheat_Sheet (all this case-insensitive and inserting meaningless characters technics). I guess many of them don't work in modern browsers but it's better to be safe than sorry.
