### ISSUE TITLE
Factor out search/replace functionality into a separate class

### ISSUE THREAD

**Issue by gregjacobs** [gregjacobs/Autolinker.js#74]
To allow direct searching/replacing non-html strings.

Discussion in #67 

CC @puzrin

**Comment by puzrin** [comment]
https://github.com/markdown-it/linkexp

It's not complete yet (some tests fails when enabled). Positioned as low level lib to write linkifiers.

**Comment by puzrin** [comment]
@gregjacobs i published first version. Here you can play with online demo http://markdown-it.github.io/linkify-it/ . Let me know if you need something there.

**Comment by gregjacobs** [comment]
Forgot about this issue :satisfied:

Autolinker has supported `.link()` and `.parse()` methods for a while now.

Great job on yours though @puzrin! Random tidbit, I came across your `markdown-it` project just the other day when looking for a markdown parser :)
