### ISSUE TITLE
'&' at the end of a valid URL parses incorrectly

### ISSUE THREAD

**Issue by Cogito** [gregjacobs/Autolinker.js#76]
"google.com&" should parse to "<a href='google.com'>google.com</a>&" but is instead parsed to "<a href='google.com&'>google.com&</a>"

"google.com&" is not a valid URL

**Comment by mcmaniac** [comment]
+1

Could possibly be solved by adding `&quot;` to the `htmlCharacterEntitiesRegex` ? I did this as a temporary workaround and it seems to work:

            var autolinker = new Autolinker();
            // FIXME: workaround for https://github.com/gregjacobs/Autolinker.js/issues/76
            autolinker.htmlCharacterEntitiesRegex = /(&nbsp;|&#160;|&lt;|&#60;|&gt;|&#62;|&quot;|&#34;|&#39;)/gi;

This adds the regex for both " and '.

**Comment by gregjacobs** [comment]
Fixed in [0.15.2](https://github.com/gregjacobs/Autolinker.js/releases/tag/0.15.2)
