### ISSUE TITLE
Should it autolink Twitter hashtags too?

### ISSUE THREAD

**Issue by alexanderdickson** [gregjacobs/Autolinker.js#78]
It may make sense as it's picking up `@usernames`.

**Comment by calabroa** [comment]
+1

**Comment by SamKO91** [comment]
Added the feature in my fork and made a pull request, hopefully it will get accepted and added to this repo

**Comment by gregjacobs** [comment]
Added (finally) in [v0.17.0](https://github.com/gregjacobs/Autolinker.js/releases/tag/0.17.0]). (Thanks @SamKO91) Example:

```javascript
Autolinker.link( "#myHashTag", { hashtag: 'twitter' } );
```
