### ISSUE TITLE
New truncate option to place the ellipsis in the middle of links

### ISSUE THREAD

**Issue by kafoso** [gregjacobs/Autolinker.js#85]
The truncate feature is lovely. However, to me, links ending on periods look down-right weird. That, of course, is my personal preference, but others agree with me.

In any case, I've noticed that many software applications, including Google Chrome and Skype, truncate (long) links in the middle. Most commonly - if possible - the truncation occurs between slashes (in the relative URI) or ampersands in the query (`?`) and/or fragment (`#`) part of the URL.

E.g. this:

```
https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&es_th=1&ie=UTF-8#q=github&es_th=1
```

... would become something like this:

```
https://www.google.com/webhp?sourceid=chrome-instant&...&es_th=1
```

.. all, of course, depending on the number of characters to be truncated.

I can do a pull request for this feature, if interested?

**Comment by gregjacobs** [comment]
Hey man, so sorry for the super late reply... 100% agree with this change, and that's actually how I wanted to do it originally, but now can't remember what made me change it.. (I think one of my co-workers at the time argued against it for some reason.)

Would def appreciate a pull request!

**Comment by devonzara** [comment]
I too would love to see this, though I'm not certain as to the best way to go about it...

A rather simple/untested approach might be something like:
https://regex101.com/r/bW5pM2/1

**Comment by kafoso** [comment]
I totally forgot this one. Somehow I've unwatched the repo. My apologies!

I'll look at it soon and get a PR ready for you guys.

**Comment by simison** [comment]
+1

**Comment by devonzara** [comment]
Sounds great, @kafoso! I'll be looking forward to seeing that PR. :+1:

**Comment by gregjacobs** [comment]
Added in [v0.20.0](https://github.com/gregjacobs/Autolinker.js/releases/tag/0.20.0) :)
