### ISSUE TITLE
webpack (6to5) require/import problem 

### ISSUE THREAD

**Issue by max-mykhailenko** [gregjacobs/Autolinker.js#86]
I tried to use autolinker from npm module

And after import
`import Autolinker from 'autolinker';`

get this
`Uncaught TypeError: Cannot set property 'returnExportsGlobal' of undefined`

In code

```
(function (root, factory) {
    if (true) {
        // AMD. Register as an anonymous module.
        !(__WEBPACK_AMD_DEFINE_ARRAY__ = [], __WEBPACK_AMD_DEFINE_RESULT__ = function () {
            return root.returnExportsGlobal = factory();
        }.apply(exports, __WEBPACK_AMD_DEFINE_ARRAY__), __WEBPACK_AMD_DEFINE_RESULT__ !== undefined && (module.exports = __WEBPACK_AMD_DEFINE_RESULT__));
    } else if (typeof exports === "object") {
        // Node. Does not work with strict CommonJS, but
        // only CommonJS-like enviroments that support module.exports,
        // like Node.
        module.exports = factory();
    } else {
        root.Autolinker = factory();
    }
})(undefined, function () {                // why this undefined?
... // autolinker here
```

**Comment by max-mykhailenko** [comment]
if I changed https://github.com/gregjacobs/Autolinker.js/blob/master/dist/Autolinker.js#L2
to if (root && typeof define === 'function' && define.amd) { 
all works fine.

**Comment by max-mykhailenko** [comment]
Where I can change it in forked version?

**Comment by iam4x** [comment]
bump! need this!

**Comment by gregjacobs** [comment]
Hey guys, sorry for the late reply. Not sure exactly what you're doing here though. What do you have installed to give you that `import` statement?

**Comment by max-mykhailenko** [comment]
`import` or `require` provided by babel and webpack

**Comment by LeZuse** [comment]
Just used this to fix the issue with Webpack `import` and it works flawlessly.

**Comment by MadLittleMods** [comment]
:+1: I am also running into this webpack issue. The [solution proposed by @max-mykhailenko works](https://github.com/gregjacobs/Autolinker.js/issues/86#issuecomment-74487812) but I assume messes with other environments.

**Comment by LeZuse** [comment]
Are you guys also using Babel? I think what we are running into here is [Babel strict mode](https://babeljs.io/docs/plugins/transform-strict-mode/). It is turned off by default in Babel 6. See http://stackoverflow.com/a/33821820/303016

**Comment by prashanth1509** [comment]
{ test: /\.js$/, loader: 'imports?define=>false'} should fix it.

**Comment by gregjacobs** [comment]
Not sure if anyone is still having an issue with this 3 years later, but feel free to reopen if needed 😄
