### ISSUE TITLE
The character ' breaks the link

### ISSUE THREAD

**Issue by Torsph** [gregjacobs/Autolinker.js#90]
On google you may get links like this:
"google.no/maps/place/Gary's+Deli/@52.3664378,4.869345,18z/data=!4m7!1m4!3m3!1s0x47c609c14a6680df:0x643f005113531f15!2sBeertemple!3b1!3m1!1s0x0000000000000000:0x51a8a6adb4307be6?hl=no"

It will break of Gary's and stop the link there. Do you have any solution to this?

**Comment by gregjacobs** [comment]
Hey, sorry for the late reply. Which version of Autolinker are you using? This should work as of v0.12.5, but v0.17.0 is the latest and it works correctly on that version.

Let me know if you're still having an issue though!
