### ISSUE TITLE
Optional prevent from linkifying patterns, without "http", "www".

### ISSUE THREAD

**Issue by atsoy** [gregjacobs/Autolinker.js#91]
It works great for all cases with `stripPrefix: false`. Input:

```
http://google.com
www.google.com
google.com
```

Output:
```
<a href="http://google.com" target="_blank">http://google.com</a>
<a href="http://www.google.com" target="_blank">http://www.google.com</a>
<a href="http://google.com" target="_blank">http://google.com</a>
```

But i would like to prevent Autolinker.link() from linkifying patterns without `www`. Is that possible in current version? 

From example above:

`google.com`should stay `google.com` as a plain text without changes.

**Comment by gregjacobs** [comment]
Hey atsoy. Just want to confirm what you're looking for: You want to autolink 'http://google.com' and 'www.google.com', but *not* autolink the text 'google.com'?

**Comment by atsoy** [comment]
Hi Greg,

thank you for your reply!

Yes, correct.

**Comment by bjm904** [comment]
I would like this feature too.

**Comment by dmr** [comment]
@gregjacobs Do you have an opinion on this feature?
I'd like to use autolinker but I need this feature!

**Comment by i-kaplin** [comment]
+1 for this feature.

**Comment by fntneves** [comment]
+1 too

**Comment by khakulov** [comment]
+1

**Comment by gregjacobs** [comment]
Hey all. Very late, I know... Finally have some time to work on this!

Thinking some customization in the options to allow for this. Maybe something like:

```
Autolinker.link( text, {
    urls : {
        schemeMatches: true,
        wwwMatches: true,
        tldMatches: false  // top level domain matches without a scheme or 'www'
    }
} );
```

Thoughts?

**Comment by simison** [comment]
@gregjacobs Seems pretty flexible to me!

**Comment by fntneves** [comment]
@gregjacobs I like it too !

**Comment by dmr** [comment]
@gregjacobs Sounds great!

**Comment by gregjacobs** [comment]
Awesome. Ok, will do!

**Comment by gregjacobs** [comment]
Ok, added in [v0.22.0](https://github.com/gregjacobs/Autolinker.js/releases/tag/0.22.0). Let me know how it goes!
