### ISSUE TITLE
Please add Autolinker.js to jsDeliver and/or CDNJS

### ISSUE THREAD

**Issue by gdelprete** [gregjacobs/Autolinker.js#94]
It would be cool to have Autolinker.js pushed to CDNs for us non-heady-Javascript developer.

I'm willing to try doing it for jsDeliver if you want.

**Comment by gregjacobs** [comment]
Yes, that would be great if you have some time!

**Comment by gdelprete** [comment]
This is now done.

**Comment by gregjacobs** [comment]
Awesome, thanks!!
