### ISSUE TITLE
Please improve telephone number recognition

### ISSUE THREAD

**Issue by gdelprete** [gregjacobs/Autolinker.js#95]
International phone numbers starting with the + symbol seem not recognized. Note that all the possible international prefixes are known (a list can be found at http://en.wikipedia.org/wiki/List_of_country_calling_codes ) so the regexp could be very strict. Something like:
`\+(code1|code2|...)[ \-\(\)0-9]{3,}`
(or possible requiring an even longer sequence of digits to protect from recognizing numbers with a leading explicit positive sign).

Right now the regex recognizes only numbers roughtly in US format (XXX) XXX-XXXX .

**Comment by gdelprete** [comment]
Oops, sorry, it looks like the regexp should already handle international number. However, we format them as:
``+1 202-371-2121`` 
and it looks like they are not recognized.

**Comment by gregjacobs** [comment]
Hey, thanks for the info. Great to know. Will update for this.

**Comment by mfc-julius** [comment]
English numbers, e.g. 020 1111 1111 are not being recognised also.

**Comment by simison** [comment]
Here's an example:

http://rubular.com/r/Ljut8sn7oS

(Regex from https://github.com/gregjacobs/Autolinker.js/blob/master/src/matchParser/MatchParser.js#L108 )

Seems like it doesn't stop on newlines either.

**Comment by simison** [comment]
@gdelprete @mfc-julius @gregjacobs would this work better:

http://rubular.com/r/KzyezB1d0I

`((\+|00)[1-9]{1}[0-9\040]{7,14})|((?:(\+)?\d{1,3}[-\040.])?\(?\d{3}\)?[-\040.]?\d{3}[-\040.]\d{4})`

It basically has its own part for European numbers and second part for the rest.

Thoughts?

**Comment by gregjacobs** [comment]
Nicely done. Let me give this a try and I'll let you know!

**Comment by simison** [comment]
FYI; I wanted to do more checking on length of the European numbers `{7,14}` — but didn't yet find time to dig more.

**Comment by simison** [comment]
FYI, this looks interesting: https://github.com/chriso/validator.js/blob/master/validator.js#L83-L100

**Comment by simison** [comment]
Woah. So Google's phone number i18n [recognition is massive](https://github.com/googlei18n/libphonenumber/blob/master/javascript/i18n/phonenumbers/metadata.js)

**Comment by garychapman** [comment]
@gregjacobs Would it be possible to make the various regex patterns externally configurable? We'd love it if Autolinker could recognise various Australian phone numbers.

**Comment by christiandawson** [comment]
#196 is a PR that attempts to solve this issue, please review

**Comment by olafleur** [comment]
Closing. Will follow the idea of having an externally configurable regex in #202 .
