### ISSUE TITLE
Hashtags not linking with Custom Replace Function

### ISSUE THREAD

**Issue by jacobedawson** [gregjacobs/Autolinker.js#96]
Hi - I love Autolinker, it's really useful! I'm having an issue though using the 'replaceFn' so that I can replace mentions & hashtags with my own urls. The thing is, @mentions are working fine, but hashtags are not. Below is the code that I'm using (as part of a much larger function):

    msg = Autolinker.link( msg, {
                replaceFn : function( autolinker, match ) {
                    switch( match.getType() ) {

                        case 'twitter' :
                           //THIS WORKS PERFECTLY
                            var twitterHandle = match.getTwitterHandle();
                            return '<a href=\"/user/' + twitterHandle + '\">@' + twitterHandle + '</a>';

                        case 'hashtag' :
                            //THIS IS NOT BEING RETURNED EVEN WHEN THERE ARE HASHTAGS
                            var hashtag = match.getHashtag();
                            return '<a href=\"/hashtag/' + hashtag + '\">#' + hashtag + '</a>';

                    }
                }
            });

If anyone can point out what I'm doing wrong / neglecting here I'd really appreciate it!!

Cheers, 

Jake

**Comment by jacobedawson** [comment]
Still looking for an answer for this one, I've tried several different things and looked through the docs, but I'm completely stumped :(

**Comment by metatribal** [comment]
the hashtag option defaults to false.  I have worked around this by setting the option {hashtag: 'twitter'}  The replaceFN then executes as expected.  You may need to remove the twitter case from your switch statement (I did)

**Comment by jacobedawson** [comment]
@metatribal Thanks a lot for replying - I'll change the code when I get home from work :) I appreciated your help!

Cheers, 

Jake

**Comment by jacobedawson** [comment]
Hi @metatribal - I tried this out but this actually took me back to square 1, because it is linking to twitter.com - the reason that I'm using the replaceFn is because I would like to have Autolinker replace hashtags with links to my own domain - in the above code you can see that I'm using a relative URL. 

This works fine for @ mentions, but it isn't working for hashtags. Does that make sense? If you have any additional tips about how I can achieve this it would be great :) 

Cheers, 

Jake

**Comment by gregjacobs** [comment]
So sorry for the late response Jake.. 

Looking to build something a bit different for hashtags, as suggested in #130.

In the meantime, @metatribal's suggestion should have worked. Setting `hashtag` to 'twitter' should cause Autolinker to match hashtags in the input text, and provide them to the `replaceFn`. If you're still having an issue (I know it's a number of months later.. lol), feel free to reopen and post your input text and I'll take a look. Make sure you grab the latest version too first (v0.22.0) - might have been a bug in an older version

**Comment by adamgins** [comment]
@gregjacobs great package. I have been using in default state in production for ages. Thanks.
I wanted to customize some of the mentions, I am having a similar issues to this issue of getting the `replaceFn` to fire. 

I have initialized the autolinker with 

```
var Autolinker = require( 'autolinker' );
var autolinker = new Autolinker( {
    urls : {
        schemeMatches : true,
        wwwMatches    : true,
        tldMatches    : true
    },
    email       : true,
    phone       : true,
    mention     : 'twitter',
    hashtag     : 'twitter',

    stripPrefix : true,
    newWindow   : true,

    truncate : {
        length   : 0,
        location : 'end'
    },

    className : ''
} );
```

then I call it like so

```
var linkedText = autolinker.link( inputText, {
                replaceFn : function( match ) {
                    console.log( "href = ", match.getAnchorHref() );
                    console.log( "text = ", match.getAnchorText() );
                    console.log("INPUTTEXT:", inputText, "MATCH TYPE:", match.getType(), match )

                    switch( match.getType() ) {
                        case 'url' :
                            console.log( "url: ", match.getUrl() );

                            return true;  // let Autolinker perform its normal anchor tag replacement

                        case 'email' :
                            var email = match.getEmail();
                            console.log( "email: ", email );

                            if( email === "my@own.address" ) {
                                return false;  // don't auto-link this particular email address; leave as-is
                            } else {
                                return;  // no return value will have Autolinker perform its normal anchor tag replacement (same as returning `true`)
                            }

                        case 'phone' :
                            console.log( "Phone Number: ", match.getNumber() );

                            return '<a href="http://newplace.to.link.phone.numbers.to/">' + match.getNumber() + '</a>';

                        case 'mention' :
                            console.log( "Mention: ", match.getMention() );
                            console.log( "Mention Service Name: ", match.getServiceName() );

                            return '<a href="http://newplace.to.link.mention.handles.to/">' + match.getMention() + '</a>';

                        case 'hashtag' :
                            console.log( "Hashtag: ", match.getHashtag() );

                            return '<a href="http://newplace.to.link.hashtag.handles.to/">' + match.getHashtag() + '</a>';
                    }
                }
            });
            return linkedText;
```
But the `console.log`s  below never fire. Any ideas pls?

```
 console.log( "href = ", match.getAnchorHref() );
                    console.log( "text = ", match.getAnchorText() );
                    console.log("INPUTTEXT:", inputText, "MATCH TYPE:", match.getType(), match )
```

**Comment by olafleur** [comment]
I would recommend opening another issue to not get your message lost. :)

**Comment by adamgins** [comment]
@olafleur thanks. created #199

**Comment by shubhdhawan** [comment]
> @gregjacobs great package. I have been using in default state in production for ages. Thanks.
> I wanted to customize some of the mentions, I am having a similar issues to this issue of getting the `replaceFn` to fire.
> 
> I have initialized the autolinker with
> 
> ```
> var Autolinker = require( 'autolinker' );
> var autolinker = new Autolinker( {
>     urls : {
>         schemeMatches : true,
>         wwwMatches    : true,
>         tldMatches    : true
>     },
>     email       : true,
>     phone       : true,
>     mention     : 'twitter',
>     hashtag     : 'twitter',
> 
>     stripPrefix : true,
>     newWindow   : true,
> 
>     truncate : {
>         length   : 0,
>         location : 'end'
>     },
> 
>     className : ''
> } );
> ```
> 
> then I call it like so
> 
> ```
> var linkedText = autolinker.link( inputText, {
>                 replaceFn : function( match ) {
>                     console.log( "href = ", match.getAnchorHref() );
>                     console.log( "text = ", match.getAnchorText() );
>                     console.log("INPUTTEXT:", inputText, "MATCH TYPE:", match.getType(), match )
> 
>                     switch( match.getType() ) {
>                         case 'url' :
>                             console.log( "url: ", match.getUrl() );
> 
>                             return true;  // let Autolinker perform its normal anchor tag replacement
> 
>                         case 'email' :
>                             var email = match.getEmail();
>                             console.log( "email: ", email );
> 
>                             if( email === "my@own.address" ) {
>                                 return false;  // don't auto-link this particular email address; leave as-is
>                             } else {
>                                 return;  // no return value will have Autolinker perform its normal anchor tag replacement (same as returning `true`)
>                             }
> 
>                         case 'phone' :
>                             console.log( "Phone Number: ", match.getNumber() );
> 
>                             return '<a href="http://newplace.to.link.phone.numbers.to/">' + match.getNumber() + '</a>';
> 
>                         case 'mention' :
>                             console.log( "Mention: ", match.getMention() );
>                             console.log( "Mention Service Name: ", match.getServiceName() );
> 
>                             return '<a href="http://newplace.to.link.mention.handles.to/">' + match.getMention() + '</a>';
> 
>                         case 'hashtag' :
>                             console.log( "Hashtag: ", match.getHashtag() );
> 
>                             return '<a href="http://newplace.to.link.hashtag.handles.to/">' + match.getHashtag() + '</a>';
>                     }
>                 }
>             });
>             return linkedText;
> ```
> 
> But the `console.log`s below never fire. Any ideas pls?
> 
> ```
>  console.log( "href = ", match.getAnchorHref() );
>                     console.log( "text = ", match.getAnchorText() );
>                     console.log("INPUTTEXT:", inputText, "MATCH TYPE:", match.getType(), match )
> ```

I am having the same problem how did you resolved this
